# Generated by Django 2.2.9 on 2020-02-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kasa', '0003_auto_20200209_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
