# Generated by Django 2.2.9 on 2020-02-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kasa', '0004_songs_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='content',
            field=models.TextField(blank=True, verbose_name='앨범소개'),
        ),
    ]
