# Generated by Django 2.2.9 on 2020-02-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kasa', '0005_albums_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='album_art',
            field=models.ImageField(upload_to='album_art', verbose_name='자켓사진'),
        ),
        migrations.AlterField(
            model_name='explanations',
            name='image',
            field=models.ImageField(blank=True, upload_to='explanation_image', verbose_name='사진'),
        ),
    ]
