# Generated by Django 2.2.9 on 2020-02-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kasa', '0006_auto_20200213_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_image',
            field=models.ImageField(blank=True, upload_to='group_image', verbose_name='그룹사진'),
        ),
        migrations.AlterField(
            model_name='fandoms',
            name='official_url',
            field=models.URLField(blank=True, verbose_name='팬카페'),
        ),
    ]
