# Generated by Django 2.2.9 on 2020-02-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kasa', '0007_auto_20200214_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singers',
            name='image',
            field=models.ImageField(blank=True, upload_to='singer_image', verbose_name='가수사진'),
        ),
    ]
