# Generated by Django 2.2.9 on 2020-02-16 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Kasa', '0008_auto_20200214_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='singers',
            name='birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='생일'),
            preserve_default=False,
        ),
    ]
