# Generated by Django 2.2.9 on 2020-02-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kasa', '0009_singers_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='debut',
            field=models.DateField(default='2020-02-18', verbose_name='데뷔일'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Fandoms',
        ),
    ]
