# Generated by Django 2.2.9 on 2020-02-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kasa', '0010_auto_20200218_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='singers',
            name='active_date',
            field=models.DateField(blank=True, null=True, verbose_name='활동년대'),
        ),
        migrations.AddField(
            model_name='singers',
            name='constellation',
            field=models.CharField(blank=True, max_length=255, verbose_name='별자리'),
        ),
        migrations.AddField(
            model_name='singers',
            name='content',
            field=models.TextField(blank=True, verbose_name='가수소개'),
        ),
        migrations.AddField(
            model_name='singers',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, verbose_name='국적'),
        ),
    ]
