# Generated by Django 2.2.9 on 2020-02-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kasa', '0011_auto_20200218_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanations',
            name='lyrics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics_explanation', to='Kasa.Lyrics', verbose_name='가사'),
        ),
    ]
