# Generated by Django 2.2.9 on 2020-02-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
